[2024-04-30T08:05:08.201+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: big_data_python_demo.extract manual__2024-04-30T08:05:00.438195+00:00 [queued]>
[2024-04-30T08:05:08.214+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: big_data_python_demo.extract manual__2024-04-30T08:05:00.438195+00:00 [queued]>
[2024-04-30T08:05:08.215+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-30T08:05:08.245+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): extract> on 2024-04-30 08:05:00.438195+00:00
[2024-04-30T08:05:08.253+0000] {standard_task_runner.py:60} INFO - Started process 1708 to run task
[2024-04-30T08:05:08.258+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'big_data_python_demo', 'extract', 'manual__2024-04-30T08:05:00.438195+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/Hw2.py', '--cfg-path', '/tmp/tmp8j_9iy6l']
[2024-04-30T08:05:08.263+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract
[2024-04-30T08:05:08.345+0000] {task_command.py:423} INFO - Running <TaskInstance: big_data_python_demo.extract manual__2024-04-30T08:05:00.438195+00:00 [running]> on host f153e58ecd1c
[2024-04-30T08:05:08.507+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='big_data_python_demo' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T08:05:00.438195+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T08:05:00.438195+00:00'
[2024-04-30T08:05:08.524+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv_coktoh8 --python=python
[2024-04-30T08:05:08.540+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T08:05:10.485+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 1068ms
[2024-04-30T08:05:10.486+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv_coktoh8, clear=False, no_vcs_ignore=False, global=False)
[2024-04-30T08:05:10.487+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-30T08:05:10.488+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.1.0, wheel==0.42.0
[2024-04-30T08:05:10.490+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-30T08:05:10.577+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv_coktoh8/bin/pip install -r /tmp/venv_coktoh8/requirements.txt
[2024-04-30T08:05:10.597+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T08:05:12.839+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venv_coktoh8/requirements.txt (line 1))
[2024-04-30T08:05:13.123+0000] {process_utils.py:190} INFO -   Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-04-30T08:05:13.651+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:13.667+0000] {process_utils.py:190} INFO -   Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2024-04-30T08:05:13.974+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:13.987+0000] {process_utils.py:190} INFO -   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-04-30T08:05:14.158+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:14.172+0000] {process_utils.py:190} INFO -   Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[2024-04-30T08:05:14.240+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:14.255+0000] {process_utils.py:190} INFO -   Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-04-30T08:05:14.830+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:14.845+0000] {process_utils.py:190} INFO -   Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-04-30T08:05:14.917+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv_coktoh8/requirements.txt (line 2))
[2024-04-30T08:05:14.931+0000] {process_utils.py:190} INFO -   Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-04-30T08:05:14.971+0000] {process_utils.py:190} INFO - Downloading dill-0.3.8-py3-none-any.whl (116 kB)
[2024-04-30T08:05:14.996+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.4 MB/s eta 0:00:00
[2024-04-30T08:05:15.012+0000] {process_utils.py:190} INFO - Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2024-04-30T08:05:15.623+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 19.9 MB/s eta 0:00:00
[2024-04-30T08:05:15.640+0000] {process_utils.py:190} INFO - Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-04-30T08:05:16.415+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 20.6 MB/s eta 0:00:00
[2024-04-30T08:05:16.428+0000] {process_utils.py:190} INFO - Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-04-30T08:05:16.451+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 12.9 MB/s eta 0:00:00
[2024-04-30T08:05:16.465+0000] {process_utils.py:190} INFO - Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
[2024-04-30T08:05:16.499+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 17.8 MB/s eta 0:00:00
[2024-04-30T08:05:16.512+0000] {process_utils.py:190} INFO - Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
[2024-04-30T08:05:16.543+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 13.1 MB/s eta 0:00:00
[2024-04-30T08:05:16.559+0000] {process_utils.py:190} INFO - Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-04-30T08:05:17.187+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, tzdata, six, numpy, dill, python-dateutil, pandas
[2024-04-30T08:05:28.335+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
[2024-04-30T08:05:28.729+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv_coktoh8/bin/python /tmp/venv-callhe2f6qe4/script.py /tmp/venv-callhe2f6qe4/script.in /tmp/venv-callhe2f6qe4/script.out /tmp/venv-callhe2f6qe4/string_args.txt /tmp/venv-callhe2f6qe4/termination.log
[2024-04-30T08:05:28.741+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T08:05:29.258+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-30T08:05:29.259+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhe2f6qe4/script.py", line 56, in <module>
[2024-04-30T08:05:29.259+0000] {process_utils.py:190} INFO -     res = extract(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-30T08:05:29.260+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callhe2f6qe4/script.py", line 25, in extract
[2024-04-30T08:05:29.260+0000] {process_utils.py:190} INFO -     data = pd.read_csv("Metro_zori_uc_sfrcondomfr_sm_month.csv")
[2024-04-30T08:05:29.261+0000] {process_utils.py:190} INFO -   File "/tmp/venv_coktoh8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
[2024-04-30T08:05:29.262+0000] {process_utils.py:190} INFO -     return _read(filepath_or_buffer, kwds)
[2024-04-30T08:05:29.262+0000] {process_utils.py:190} INFO -   File "/tmp/venv_coktoh8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
[2024-04-30T08:05:29.263+0000] {process_utils.py:190} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-04-30T08:05:29.263+0000] {process_utils.py:190} INFO -   File "/tmp/venv_coktoh8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
[2024-04-30T08:05:29.264+0000] {process_utils.py:190} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-04-30T08:05:29.264+0000] {process_utils.py:190} INFO -   File "/tmp/venv_coktoh8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
[2024-04-30T08:05:29.265+0000] {process_utils.py:190} INFO -     self.handles = get_handle(
[2024-04-30T08:05:29.266+0000] {process_utils.py:190} INFO -   File "/tmp/venv_coktoh8/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
[2024-04-30T08:05:29.266+0000] {process_utils.py:190} INFO -     handle = open(
[2024-04-30T08:05:29.267+0000] {process_utils.py:190} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'Metro_zori_uc_sfrcondomfr_sm_month.csv'
[2024-04-30T08:05:29.633+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'Metro_zori_uc_sfrcondomfr_sm_month.csv'
[2024-04-30T08:05:29.640+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=big_data_python_demo, task_id=extract, execution_date=20240430T080500, start_date=20240430T080508, end_date=20240430T080529
[2024-04-30T08:05:29.659+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task extract (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: 'Metro_zori_uc_sfrcondomfr_sm_month.csv'; 1708)
[2024-04-30T08:05:29.702+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-30T08:05:29.731+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
