[2024-04-30T19:49:27.213+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:44:08.862132+00:00 [queued]>
[2024-04-30T19:49:27.224+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:44:08.862132+00:00 [queued]>
[2024-04-30T19:49:27.225+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-30T19:49:27.243+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): data_aquisition> on 2024-04-30 19:44:08.862132+00:00
[2024-04-30T19:49:27.251+0000] {standard_task_runner.py:60} INFO - Started process 4139 to run task
[2024-04-30T19:49:27.255+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'homework2_data_pipeline_demo', 'data_aquisition', 'manual__2024-04-30T19:44:08.862132+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/Hw2.py', '--cfg-path', '/tmp/tmpw_77ok6r']
[2024-04-30T19:49:27.257+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask data_aquisition
[2024-04-30T19:49:27.326+0000] {task_command.py:423} INFO - Running <TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:44:08.862132+00:00 [running]> on host f153e58ecd1c
[2024-04-30T19:49:27.435+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework2_data_pipeline_demo' AIRFLOW_CTX_TASK_ID='data_aquisition' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T19:44:08.862132+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T19:44:08.862132+00:00'
[2024-04-30T19:49:27.439+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv6jmc1bfo --python=python
[2024-04-30T19:49:27.453+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T19:49:28.505+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 407ms
[2024-04-30T19:49:28.506+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv6jmc1bfo, clear=False, no_vcs_ignore=False, global=False)
[2024-04-30T19:49:28.507+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-30T19:49:28.507+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-04-30T19:49:28.508+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-30T19:49:28.552+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6jmc1bfo/bin/pip install -r /tmp/venv6jmc1bfo/requirements.txt
[2024-04-30T19:49:28.565+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T19:49:30.131+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venv6jmc1bfo/requirements.txt (line 1))
[2024-04-30T19:49:30.135+0000] {process_utils.py:190} INFO -   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-04-30T19:49:30.170+0000] {process_utils.py:190} INFO - Collecting funcsigs (from -r /tmp/venv6jmc1bfo/requirements.txt (line 2))
[2024-04-30T19:49:30.173+0000] {process_utils.py:190} INFO -   Using cached funcsigs-1.0.2-py2.py3-none-any.whl.metadata (14 kB)
[2024-04-30T19:49:30.517+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:30.520+0000] {process_utils.py:190} INFO -   Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2024-04-30T19:49:30.764+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:30.767+0000] {process_utils.py:190} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-04-30T19:49:30.953+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:30.958+0000] {process_utils.py:190} INFO -   Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[2024-04-30T19:49:31.008+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:31.013+0000] {process_utils.py:190} INFO -   Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-04-30T19:49:31.487+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:31.491+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-04-30T19:49:31.545+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv6jmc1bfo/requirements.txt (line 3))
[2024-04-30T19:49:31.549+0000] {process_utils.py:190} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-04-30T19:49:31.565+0000] {process_utils.py:190} INFO - Using cached dill-0.3.8-py3-none-any.whl (116 kB)
[2024-04-30T19:49:31.569+0000] {process_utils.py:190} INFO - Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
[2024-04-30T19:49:31.572+0000] {process_utils.py:190} INFO - Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2024-04-30T19:49:31.691+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-04-30T19:49:31.860+0000] {process_utils.py:190} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-04-30T19:49:31.868+0000] {process_utils.py:190} INFO - Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
[2024-04-30T19:49:31.877+0000] {process_utils.py:190} INFO - Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
[2024-04-30T19:49:31.885+0000] {process_utils.py:190} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-04-30T19:49:32.373+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, funcsigs, tzdata, six, numpy, dill, python-dateutil, pandas
[2024-04-30T19:49:41.878+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 funcsigs-1.0.2 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
[2024-04-30T19:49:42.283+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6jmc1bfo/bin/python /tmp/venv-callfxk7ccej/script.py /tmp/venv-callfxk7ccej/script.in /tmp/venv-callfxk7ccej/script.out /tmp/venv-callfxk7ccej/string_args.txt /tmp/venv-callfxk7ccej/termination.log
[2024-04-30T19:49:42.294+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T19:49:42.399+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-30T19:49:42.400+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callfxk7ccej/script.py", line 68, in <module>
[2024-04-30T19:49:42.401+0000] {process_utils.py:190} INFO -     res = data_aquisition(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-30T19:49:42.402+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callfxk7ccej/script.py", line 28, in data_aquisition
[2024-04-30T19:49:42.403+0000] {process_utils.py:190} INFO -     if not os.path.isfile(data_path):
[2024-04-30T19:49:42.403+0000] {process_utils.py:190} INFO - NameError: name 'os' is not defined
[2024-04-30T19:49:42.708+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'os' is not defined
[2024-04-30T19:49:42.714+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=homework2_data_pipeline_demo, task_id=data_aquisition, execution_date=20240430T194408, start_date=20240430T194927, end_date=20240430T194942
[2024-04-30T19:49:42.734+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task data_aquisition (Process returned non-zero exit status 1.
name 'os' is not defined; 4139)
[2024-04-30T19:49:42.761+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-30T19:49:42.795+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
