[2024-05-01T19:04:42.889+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T19:04:42.901+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T19:04:42.902+0000] {taskinstance.py:2193} INFO - Starting attempt 21 of 21
[2024-05-01T19:04:42.922+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): data_acquisition> on 2024-04-30 20:55:51.830154+00:00
[2024-05-01T19:04:42.929+0000] {standard_task_runner.py:60} INFO - Started process 10606 to run task
[2024-05-01T19:04:42.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'homework2_data_pipeline_demo', 'data_acquisition', 'manual__2024-04-30T20:55:51.830154+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8c293o6l']
[2024-05-01T19:04:42.938+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask data_acquisition
[2024-05-01T19:04:43.012+0000] {task_command.py:423} INFO - Running <TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [running]> on host f153e58ecd1c
[2024-05-01T19:04:43.124+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework2_data_pipeline_demo' AIRFLOW_CTX_TASK_ID='data_acquisition' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T20:55:51.830154+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T20:55:51.830154+00:00'
[2024-05-01T19:04:43.128+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvfbylg_qp --python=python
[2024-05-01T19:04:43.143+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T19:04:44.194+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 388ms
[2024-05-01T19:04:44.195+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvfbylg_qp, clear=False, no_vcs_ignore=False, global=False)
[2024-05-01T19:04:44.196+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-05-01T19:04:44.197+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-05-01T19:04:44.198+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-05-01T19:04:44.239+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfbylg_qp/bin/pip install -r /tmp/venvfbylg_qp/requirements.txt
[2024-05-01T19:04:44.249+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T19:04:45.871+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venvfbylg_qp/requirements.txt (line 1))
[2024-05-01T19:04:45.875+0000] {process_utils.py:190} INFO -   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-05-01T19:04:45.908+0000] {process_utils.py:190} INFO - Collecting funcsigs (from -r /tmp/venvfbylg_qp/requirements.txt (line 2))
[2024-05-01T19:04:45.911+0000] {process_utils.py:190} INFO -   Using cached funcsigs-1.0.2-py2.py3-none-any.whl.metadata (14 kB)
[2024-05-01T19:04:46.256+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:46.259+0000] {process_utils.py:190} INFO -   Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2024-05-01T19:04:46.478+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:46.481+0000] {process_utils.py:190} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-05-01T19:04:46.615+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:46.618+0000] {process_utils.py:190} INFO -   Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[2024-05-01T19:04:46.667+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:46.670+0000] {process_utils.py:190} INFO -   Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-05-01T19:04:47.158+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:47.161+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-05-01T19:04:47.217+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvfbylg_qp/requirements.txt (line 3))
[2024-05-01T19:04:47.221+0000] {process_utils.py:190} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-05-01T19:04:47.240+0000] {process_utils.py:190} INFO - Using cached dill-0.3.8-py3-none-any.whl (116 kB)
[2024-05-01T19:04:47.244+0000] {process_utils.py:190} INFO - Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
[2024-05-01T19:04:47.247+0000] {process_utils.py:190} INFO - Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2024-05-01T19:04:47.294+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-05-01T19:04:47.358+0000] {process_utils.py:190} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-05-01T19:04:47.362+0000] {process_utils.py:190} INFO - Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
[2024-05-01T19:04:47.368+0000] {process_utils.py:190} INFO - Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
[2024-05-01T19:04:47.373+0000] {process_utils.py:190} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-05-01T19:04:47.872+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, funcsigs, tzdata, six, numpy, dill, python-dateutil, pandas
[2024-05-01T19:04:57.394+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 funcsigs-1.0.2 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
[2024-05-01T19:04:57.816+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvfbylg_qp/bin/python /tmp/venv-callzc8_danm/script.py /tmp/venv-callzc8_danm/script.in /tmp/venv-callzc8_danm/script.out /tmp/venv-callzc8_danm/string_args.txt /tmp/venv-callzc8_danm/termination.log
[2024-05-01T19:04:57.827+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T19:04:58.335+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-05-01T19:04:58.336+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callzc8_danm/script.py", line 68, in <module>
[2024-05-01T19:04:58.336+0000] {process_utils.py:190} INFO -     res = data_acquisition(*arg_dict["args"], **arg_dict["kwargs"])
[2024-05-01T19:04:58.337+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callzc8_danm/script.py", line 32, in data_acquisition
[2024-05-01T19:04:58.338+0000] {process_utils.py:190} INFO -     df = pd.read_csv(data_path)
[2024-05-01T19:04:58.339+0000] {process_utils.py:190} INFO -   File "/tmp/venvfbylg_qp/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
[2024-05-01T19:04:58.339+0000] {process_utils.py:190} INFO -     return _read(filepath_or_buffer, kwds)
[2024-05-01T19:04:58.340+0000] {process_utils.py:190} INFO -   File "/tmp/venvfbylg_qp/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
[2024-05-01T19:04:58.340+0000] {process_utils.py:190} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2024-05-01T19:04:58.341+0000] {process_utils.py:190} INFO -   File "/tmp/venvfbylg_qp/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
[2024-05-01T19:04:58.342+0000] {process_utils.py:190} INFO -     self._engine = self._make_engine(f, self.engine)
[2024-05-01T19:04:58.342+0000] {process_utils.py:190} INFO -   File "/tmp/venvfbylg_qp/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
[2024-05-01T19:04:58.343+0000] {process_utils.py:190} INFO -     return mapping[engine](f, **self.options)
[2024-05-01T19:04:58.343+0000] {process_utils.py:190} INFO -   File "/tmp/venvfbylg_qp/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
[2024-05-01T19:04:58.344+0000] {process_utils.py:190} INFO -     self._reader = parsers.TextReader(src, **kwds)
[2024-05-01T19:04:58.345+0000] {process_utils.py:190} INFO -   File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
[2024-05-01T19:04:58.345+0000] {process_utils.py:190} INFO - pandas.errors.EmptyDataError: No columns to parse from file
[2024-05-01T19:04:58.730+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No columns to parse from file
[2024-05-01T19:04:58.735+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=homework2_data_pipeline_demo, task_id=data_acquisition, execution_date=20240430T205551, start_date=20240501T190442, end_date=20240501T190458
[2024-05-01T19:04:58.756+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task data_acquisition (Process returned non-zero exit status 1.
No columns to parse from file; 10606)
[2024-05-01T19:04:58.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-01T19:04:58.827+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
