[2024-05-01T07:28:35.320+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T07:28:35.333+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T07:28:35.334+0000] {taskinstance.py:2193} INFO - Starting attempt 7 of 7
[2024-05-01T07:28:35.354+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): data_acquisition> on 2024-04-30 20:55:51.830154+00:00
[2024-05-01T07:28:35.361+0000] {standard_task_runner.py:60} INFO - Started process 8827 to run task
[2024-05-01T07:28:35.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'homework2_data_pipeline_demo', 'data_acquisition', 'manual__2024-04-30T20:55:51.830154+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp27z93yjj']
[2024-05-01T07:28:35.367+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask data_acquisition
[2024-05-01T07:28:35.448+0000] {task_command.py:423} INFO - Running <TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [running]> on host f153e58ecd1c
[2024-05-01T07:28:35.577+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework2_data_pipeline_demo' AIRFLOW_CTX_TASK_ID='data_acquisition' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T20:55:51.830154+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T20:55:51.830154+00:00'
[2024-05-01T07:28:35.581+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvnbt_3k95 --python=python
[2024-05-01T07:28:35.595+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T07:28:36.728+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 413ms
[2024-05-01T07:28:36.729+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvnbt_3k95, clear=False, no_vcs_ignore=False, global=False)
[2024-05-01T07:28:36.730+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-05-01T07:28:36.731+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-05-01T07:28:36.731+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-05-01T07:28:36.780+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnbt_3k95/bin/pip install -r /tmp/venvnbt_3k95/requirements.txt
[2024-05-01T07:28:36.794+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T07:28:38.395+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venvnbt_3k95/requirements.txt (line 1))
[2024-05-01T07:28:38.400+0000] {process_utils.py:190} INFO -   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-05-01T07:28:38.439+0000] {process_utils.py:190} INFO - Collecting funcsigs (from -r /tmp/venvnbt_3k95/requirements.txt (line 2))
[2024-05-01T07:28:38.444+0000] {process_utils.py:190} INFO -   Using cached funcsigs-1.0.2-py2.py3-none-any.whl.metadata (14 kB)
[2024-05-01T07:28:38.775+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:38.778+0000] {process_utils.py:190} INFO -   Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2024-05-01T07:28:39.000+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:39.003+0000] {process_utils.py:190} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-05-01T07:28:39.131+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:39.134+0000] {process_utils.py:190} INFO -   Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[2024-05-01T07:28:39.184+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:39.187+0000] {process_utils.py:190} INFO -   Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-05-01T07:28:39.658+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:39.663+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-05-01T07:28:39.716+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvnbt_3k95/requirements.txt (line 3))
[2024-05-01T07:28:39.719+0000] {process_utils.py:190} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-05-01T07:28:39.736+0000] {process_utils.py:190} INFO - Using cached dill-0.3.8-py3-none-any.whl (116 kB)
[2024-05-01T07:28:39.739+0000] {process_utils.py:190} INFO - Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
[2024-05-01T07:28:39.742+0000] {process_utils.py:190} INFO - Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2024-05-01T07:28:39.783+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-05-01T07:28:39.842+0000] {process_utils.py:190} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-05-01T07:28:39.845+0000] {process_utils.py:190} INFO - Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
[2024-05-01T07:28:39.850+0000] {process_utils.py:190} INFO - Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
[2024-05-01T07:28:39.854+0000] {process_utils.py:190} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-05-01T07:28:40.334+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, funcsigs, tzdata, six, numpy, dill, python-dateutil, pandas
[2024-05-01T07:28:49.278+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 funcsigs-1.0.2 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
[2024-05-01T07:28:49.770+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnbt_3k95/bin/python /tmp/venv-calljcgu0nbp/script.py /tmp/venv-calljcgu0nbp/script.in /tmp/venv-calljcgu0nbp/script.out /tmp/venv-calljcgu0nbp/string_args.txt /tmp/venv-calljcgu0nbp/termination.log
[2024-05-01T07:28:49.782+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T07:28:50.291+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-05-01T07:28:50.292+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calljcgu0nbp/script.py", line 62, in <module>
[2024-05-01T07:28:50.293+0000] {process_utils.py:190} INFO -     res = data_acquisition(*arg_dict["args"], **arg_dict["kwargs"])
[2024-05-01T07:28:50.294+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calljcgu0nbp/script.py", line 32, in data_acquisition
[2024-05-01T07:28:50.294+0000] {process_utils.py:190} INFO -     with open(data_path, "w") as file:
[2024-05-01T07:28:50.295+0000] {process_utils.py:190} INFO - IsADirectoryError: [Errno 21] Is a directory: '/storage/acquire/'
[2024-05-01T07:28:50.706+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 21] Is a directory: '/storage/acquire/'
[2024-05-01T07:28:50.712+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=homework2_data_pipeline_demo, task_id=data_acquisition, execution_date=20240430T205551, start_date=20240501T072835, end_date=20240501T072850
[2024-05-01T07:28:50.734+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 109 for task data_acquisition (Process returned non-zero exit status 1.
[Errno 21] Is a directory: '/storage/acquire/'; 8827)
[2024-05-01T07:28:50.752+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-01T07:28:50.781+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
