[2024-05-01T18:59:45.784+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T18:59:45.797+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [queued]>
[2024-05-01T18:59:45.798+0000] {taskinstance.py:2193} INFO - Starting attempt 19 of 19
[2024-05-01T18:59:45.818+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): data_acquisition> on 2024-04-30 20:55:51.830154+00:00
[2024-05-01T18:59:45.825+0000] {standard_task_runner.py:60} INFO - Started process 10441 to run task
[2024-05-01T18:59:45.829+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'homework2_data_pipeline_demo', 'data_acquisition', 'manual__2024-04-30T20:55:51.830154+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpu_37cp34']
[2024-05-01T18:59:45.831+0000] {standard_task_runner.py:88} INFO - Job 141: Subtask data_acquisition
[2024-05-01T18:59:45.895+0000] {task_command.py:423} INFO - Running <TaskInstance: homework2_data_pipeline_demo.data_acquisition manual__2024-04-30T20:55:51.830154+00:00 [running]> on host f153e58ecd1c
[2024-05-01T18:59:46.004+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework2_data_pipeline_demo' AIRFLOW_CTX_TASK_ID='data_acquisition' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T20:55:51.830154+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T20:55:51.830154+00:00'
[2024-05-01T18:59:46.008+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv2d4j1kyk --python=python
[2024-05-01T18:59:46.021+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T18:59:47.119+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 431ms
[2024-05-01T18:59:47.120+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv2d4j1kyk, clear=False, no_vcs_ignore=False, global=False)
[2024-05-01T18:59:47.120+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-05-01T18:59:47.121+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-05-01T18:59:47.122+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-05-01T18:59:47.187+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv2d4j1kyk/bin/pip install -r /tmp/venv2d4j1kyk/requirements.txt
[2024-05-01T18:59:47.201+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T18:59:48.895+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venv2d4j1kyk/requirements.txt (line 1))
[2024-05-01T18:59:48.898+0000] {process_utils.py:190} INFO -   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-05-01T18:59:48.929+0000] {process_utils.py:190} INFO - Collecting funcsigs (from -r /tmp/venv2d4j1kyk/requirements.txt (line 2))
[2024-05-01T18:59:48.932+0000] {process_utils.py:190} INFO -   Using cached funcsigs-1.0.2-py2.py3-none-any.whl.metadata (14 kB)
[2024-05-01T18:59:49.247+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:49.250+0000] {process_utils.py:190} INFO -   Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2024-05-01T18:59:49.453+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:49.457+0000] {process_utils.py:190} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-05-01T18:59:49.585+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:49.588+0000] {process_utils.py:190} INFO -   Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[2024-05-01T18:59:49.636+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:49.639+0000] {process_utils.py:190} INFO -   Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-05-01T18:59:50.133+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:50.137+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-05-01T18:59:50.192+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv2d4j1kyk/requirements.txt (line 3))
[2024-05-01T18:59:50.195+0000] {process_utils.py:190} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-05-01T18:59:50.215+0000] {process_utils.py:190} INFO - Using cached dill-0.3.8-py3-none-any.whl (116 kB)
[2024-05-01T18:59:50.221+0000] {process_utils.py:190} INFO - Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
[2024-05-01T18:59:50.225+0000] {process_utils.py:190} INFO - Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2024-05-01T18:59:50.285+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-05-01T18:59:50.368+0000] {process_utils.py:190} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-05-01T18:59:50.373+0000] {process_utils.py:190} INFO - Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
[2024-05-01T18:59:50.379+0000] {process_utils.py:190} INFO - Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
[2024-05-01T18:59:50.383+0000] {process_utils.py:190} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-05-01T18:59:51.049+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, funcsigs, tzdata, six, numpy, dill, python-dateutil, pandas
[2024-05-01T18:59:59.998+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 funcsigs-1.0.2 numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2024.1 six-1.16.0 tzdata-2024.1
[2024-05-01T19:00:00.425+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv2d4j1kyk/bin/python /tmp/venv-call0hba1aiw/script.py /tmp/venv-call0hba1aiw/script.in /tmp/venv-call0hba1aiw/script.out /tmp/venv-call0hba1aiw/string_args.txt /tmp/venv-call0hba1aiw/termination.log
[2024-05-01T19:00:00.437+0000] {process_utils.py:186} INFO - Output:
[2024-05-01T19:00:00.997+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-05-01T19:00:00.998+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0hba1aiw/script.py", line 63, in <module>
[2024-05-01T19:00:00.999+0000] {process_utils.py:190} INFO -     res = data_acquisition(*arg_dict["args"], **arg_dict["kwargs"])
[2024-05-01T19:00:00.999+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0hba1aiw/script.py", line 30, in data_acquisition
[2024-05-01T19:00:01.000+0000] {process_utils.py:190} INFO -     raise FileNotFoundError(f"The file '{data_id}' does not exist in the '/storage/acquire/' folder.")
[2024-05-01T19:00:01.001+0000] {process_utils.py:190} INFO - FileNotFoundError: The file 'filename.csv' does not exist in the '/storage/acquire/' folder.
[2024-05-01T19:00:01.341+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The file 'filename.csv' does not exist in the '/storage/acquire/' folder.
[2024-05-01T19:00:01.347+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=homework2_data_pipeline_demo, task_id=data_acquisition, execution_date=20240430T205551, start_date=20240501T185945, end_date=20240501T190001
[2024-05-01T19:00:01.369+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 141 for task data_acquisition (Process returned non-zero exit status 1.
The file 'filename.csv' does not exist in the '/storage/acquire/' folder.; 10441)
[2024-05-01T19:00:01.395+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-01T19:00:01.424+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
