[2024-04-30T20:25:26.988+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:51:15.036853+00:00 [queued]>
[2024-04-30T20:25:27.001+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:51:15.036853+00:00 [queued]>
[2024-04-30T20:25:27.002+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-30T20:25:27.023+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): data_aquisition> on 2024-04-30 19:51:15.036853+00:00
[2024-04-30T20:25:27.030+0000] {standard_task_runner.py:60} INFO - Started process 4878 to run task
[2024-04-30T20:25:27.035+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'homework2_data_pipeline_demo', 'data_aquisition', 'manual__2024-04-30T19:51:15.036853+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/Hw2.py', '--cfg-path', '/tmp/tmpm5gj0u4a']
[2024-04-30T20:25:27.040+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask data_aquisition
[2024-04-30T20:25:27.114+0000] {task_command.py:423} INFO - Running <TaskInstance: homework2_data_pipeline_demo.data_aquisition manual__2024-04-30T19:51:15.036853+00:00 [running]> on host f153e58ecd1c
[2024-04-30T20:25:27.216+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework2_data_pipeline_demo' AIRFLOW_CTX_TASK_ID='data_aquisition' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T19:51:15.036853+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T19:51:15.036853+00:00'
[2024-04-30T20:25:27.220+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvgk6al2vb --python=python
[2024-04-30T20:25:27.233+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T20:25:28.318+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 413ms
[2024-04-30T20:25:28.319+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvgk6al2vb, clear=False, no_vcs_ignore=False, global=False)
[2024-04-30T20:25:28.320+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-04-30T20:25:28.321+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.2.0, wheel==0.43.0
[2024-04-30T20:25:28.321+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-04-30T20:25:28.366+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvgk6al2vb/bin/pip install -r /tmp/venvgk6al2vb/requirements.txt
[2024-04-30T20:25:28.379+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T20:25:29.925+0000] {process_utils.py:190} INFO - Collecting dill (from -r /tmp/venvgk6al2vb/requirements.txt (line 1))
[2024-04-30T20:25:29.929+0000] {process_utils.py:190} INFO -   Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
[2024-04-30T20:25:29.965+0000] {process_utils.py:190} INFO - Collecting funcsigs (from -r /tmp/venvgk6al2vb/requirements.txt (line 2))
[2024-04-30T20:25:29.969+0000] {process_utils.py:190} INFO -   Using cached funcsigs-1.0.2-py2.py3-none-any.whl.metadata (14 kB)
[2024-04-30T20:25:29.987+0000] {process_utils.py:190} INFO - Using cached dill-0.3.8-py3-none-any.whl (116 kB)
[2024-04-30T20:25:29.991+0000] {process_utils.py:190} INFO - Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
[2024-04-30T20:25:30.109+0000] {process_utils.py:190} INFO - Installing collected packages: funcsigs, dill
[2024-04-30T20:25:30.253+0000] {process_utils.py:190} INFO - Successfully installed dill-0.3.8 funcsigs-1.0.2
[2024-04-30T20:25:30.567+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvgk6al2vb/bin/python /tmp/venv-callh_pq_scb/script.py /tmp/venv-callh_pq_scb/script.in /tmp/venv-callh_pq_scb/script.out /tmp/venv-callh_pq_scb/string_args.txt /tmp/venv-callh_pq_scb/termination.log
[2024-04-30T20:25:30.579+0000] {process_utils.py:186} INFO - Output:
[2024-04-30T20:25:30.682+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-04-30T20:25:30.684+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callh_pq_scb/script.py", line 73, in <module>
[2024-04-30T20:25:30.684+0000] {process_utils.py:190} INFO -     res = data_aquisition(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-30T20:25:30.685+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callh_pq_scb/script.py", line 23, in data_aquisition
[2024-04-30T20:25:30.686+0000] {process_utils.py:190} INFO -     import pandas as pd
[2024-04-30T20:25:30.687+0000] {process_utils.py:190} INFO - ModuleNotFoundError: No module named 'pandas'
[2024-04-30T20:25:30.760+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 478, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'pandas'
[2024-04-30T20:25:30.765+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=homework2_data_pipeline_demo, task_id=data_aquisition, execution_date=20240430T195115, start_date=20240430T202526, end_date=20240430T202530
[2024-04-30T20:25:30.800+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task data_aquisition (Process returned non-zero exit status 1.
No module named 'pandas'; 4878)
[2024-04-30T20:25:30.823+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-30T20:25:30.854+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
